const dinosaurs = [
  "Tyrannosaurus Rex",
  "Spinosaurus",
  "microraptor",
  "micropachycephalosaurus",
  "heterodontosaurus",
  "oviraptor",
  "allosaurus",
  "ankylosaurus",
  "brachiosurus",
  "giganotosaurus",
  "ornithomimus",
  "stegosaurus",
  "tricearatops",
  "velociraptor",
  "deinonychuses",
  "pteranodon",
  "albertosaurus",
  "carcharodontosaurus",
  "deltadromeus",
  "dilophosaurus",
  "argentinosaurus",
  "Edamontonia",
];
